### ISSUE TITLE
 when we tap on Submit button two or more times our App crashes

### ISSUE THREAD

**Issue by alexjheu** [SurveyMonkey/surveymonkey-android-sdk#54] opened 2018-08-28 13:56 UTC
We are seeing crashes when we tap on Submit button two or more times

NOTE: we have the Survey Monkey SDK into our Android App

Steps:

Fill in the survey everything
tap on Submit 2 or more times
App Crashes

**Comment by alexjheu** [comment] 2018-09-17 15:04
@ayeung  any update?

**Comment by ayeung** [comment] 2018-09-19 16:42
I tried to reproduce a while ago, and did not have any luck.  I tapped submit multiple times and it still went through fine.  Logs, device info and any other information would be helpful

**Comment by alexjheu** [comment] 2018-09-21 18:41
@ayeung Would we be able to schedule a call so we can show you the crash?

**Comment by ayeung** [comment] 2018-09-21 18:47
@alexjheu Would you mind trying to reproduce on the sample app in this repo?  I tried running it on that app, and it worked for me.

**Comment by alexjheu** [comment] 2018-09-21 18:50
What sample app?

**Comment by ayeung** [comment] 2018-09-21 18:52
This repo: surveymonkey-android-sdk has a sample app in it called SimpleSurvey, you just need to import this project and run it

**Comment by alexjheu** [comment] 2018-09-25 15:09
we can close this issue. My team closed this internally.

**Comment by alexjheu** [comment] 2018-09-25 19:33
@ayeung we are still able to reproduce on our end

**Comment by ayeung** [comment] 2018-09-26 21:35
I've tried this on a Galaxy S7 in the sample app with no luck. The crash log would also be helpful.

**Comment by ayeung** [comment] 2019-01-03 21:09
This is a duplicate of https://github.com/SurveyMonkey/surveymonkey-android-sdk/issues/38 and is already fixed in the latest version of the sdk

**Closed by ayeung** 2019-01-03 21:09 UTC
