### ISSUE TITLE
 java.lang.IllegalArgumentException: Receiver not registered: null

### ISSUE THREAD

**Issue by SergeyDivak** [SurveyMonkey/surveymonkey-android-sdk#39] opened 2017-08-04 07:54 UTC
java.lang.RuntimeException: Unable to destroy activity {mypackage/com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackActivity}: java.lang.IllegalArgumentException: Receiver not registered: null
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3374)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3392)
	at android.app.ActivityThread.access$1200(ActivityThread.java:130)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1264)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4847)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:535)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: null
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:656)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1162)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:378)
	at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment.onDestroy(SMFeedbackFragment.java)
	at android.support.v4.app.Fragment.performDestroy(Fragment.java)
	at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java)
	                                              shouldRunOnHWLayer(FragmentManagerImpl.java)
	                                              throwException(FragmentManagerImpl.java)
	                                              beginTransaction(FragmentManagerImpl.java)
	                                              popBackStack(FragmentManagerImpl.java)
	                                              popBackStackImmediate(FragmentManagerImpl.java)
	                                              putFragment(FragmentManagerImpl.java)
	                                              getFragment(FragmentManagerImpl.java)
	                                              dump(FragmentManagerImpl.java)
	                                              makeOpenCloseAnimation(FragmentManagerImpl.java)
	                                              makeFadeAnimation(FragmentManagerImpl.java)
	                                              loadAnimation(FragmentManagerImpl.java)
	                                              performPendingDeferredStart(FragmentManagerImpl.java)
	                                              moveToState(FragmentManagerImpl.java)
	                                              addFragment(FragmentManagerImpl.java)
	                                              findFragmentById(FragmentManagerImpl.java)
	                                              findFragmentByTag(FragmentManagerImpl.java)
	                                              enqueueAction(FragmentManagerImpl.java)
	                                              allocBackStackIndex(FragmentManagerImpl.java)
	                                              setBackStackIndex(FragmentManagerImpl.java)
	                                              executePostponedTransaction(FragmentManagerImpl.java)
	                                              executeOpsTogether(FragmentManagerImpl.java)
	                                              makeRemovedFragmentsInvisible(FragmentManagerImpl.java)
	                                              postponePostponableTransactions(FragmentManagerImpl.java)
	                                              completeExecute(FragmentManagerImpl.java)
	                                              popBackStackState(FragmentManagerImpl.java)
	                                              restoreAllState(FragmentManagerImpl.java)
	                                              attachController(FragmentManagerImpl.java)
	                                              dispatchMultiWindowModeChanged(FragmentManagerImpl.java)
	                                              dispatchConfigurationChanged(FragmentManagerImpl.java)
	                                              dispatchCreateOptionsMenu(FragmentManagerImpl.java)
	                                              dispatchPrepareOptionsMenu(FragmentManagerImpl.java)
	                                              dispatchOptionsItemSelected(FragmentManagerImpl.java)
	                                              dispatchOnFragmentPreAttached(FragmentManagerImpl.java)
	                                              dispatchOnFragmentCreated(FragmentManagerImpl.java)
	                                              dispatchOnFragmentViewCreated(FragmentManagerImpl.java)
	                                              onCreateView(FragmentManagerImpl.java)
	                                              access$200(FragmentManagerImpl.java)
	                                              access$300(FragmentManagerImpl.java)
	at android.support.v4.app.FragmentManagerImpl.getBackStackEntryCount(FragmentManagerImpl.java)
	                                              moveFragmentToExpectedState(FragmentManagerImpl.java)
	                                              dispatchOnFragmentPaused(FragmentManagerImpl.java)
	                                              reverseTransit(FragmentManagerImpl.java)
	at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java)
	                                              shouldRunOnHWLayer(FragmentManagerImpl.java)
	                                              throwException(FragmentManagerImpl.java)
	                                              beginTransaction(FragmentManagerImpl.java)
	                                              popBackStack(FragmentManagerImpl.java)
	                                              popBackStackImmediate(FragmentManagerImpl.java)
	                                              putFragment(FragmentManagerImpl.java)
	                                              getFragment(FragmentManagerImpl.java)
	                                              dump(FragmentManagerImpl.java)
	                                              makeOpenCloseAnimation(FragmentManagerImpl.java)
	                                              makeFadeAnimation(FragmentManagerImpl.java)
	                                              loadAnimation(FragmentManagerImpl.java)
	                                              performPendingDeferredStart(FragmentManagerImpl.java)
	                                              moveToState(FragmentManagerImpl.java)
	                                              addFragment(FragmentManagerImpl.java)
	                                              findFragmentById(FragmentManagerImpl.java)
	                                              findFragmentByTag(FragmentManagerImpl.java)
	                                              enqueueAction(FragmentManagerImpl.java)
	                                              allocBackStackIndex(FragmentManagerImpl.java)
	                                              setBackStackIndex(FragmentManagerImpl.java)
	                                              executePostponedTransaction(FragmentManagerImpl.java)
	                                              executeOpsTogether(FragmentManagerImpl.java)
	                                              makeRemovedFragmentsInvisible(FragmentManagerImpl.java)
	                                              postponePostponableTransactions(FragmentManagerImpl.java)
	                                              completeExecute(FragmentManagerImpl.java)
	                                              popBackStackState(FragmentManagerImpl.java)
	                                              restoreAllState(FragmentManagerImpl.java)
	                                              attachController(FragmentManagerImpl.java)
	                                              dispatchMultiWindowModeChanged(FragmentManagerImpl.java)
	                                              dispatchConfigurationChanged(FragmentManagerImpl.java)
	                                              dispatchCreateOptionsMenu(FragmentManagerImpl.java)
	                                              dispatchPrepareOptionsMenu(FragmentManagerImpl.java)
	                                              dispatchOptionsItemSelected(FragmentManagerImpl.java)
	                                              dispatchOnFragmentPreAttached(FragmentManagerImpl.java)
	                                              dispatchOnFragmentCreated(FragmentManagerImpl.java)
	                                              dispatchOnFragmentViewCreated(FragmentManagerImpl.java)
	                                              onCreateView(FragmentManagerImpl.java)
	                                              access$200(FragmentManagerImpl.java)
	                                              access$300(FragmentManagerImpl.java)
	at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java)
	at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java)
	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java)
	at android.app.Activity.performDestroy(Activity.java:5351)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1134)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3361)

**Comment by doanappdev** [comment] 2017-09-08 07:22
I am getting similar crash:

```
at android.app.LoadedApk.forgetReceiverDispatcher()(LoadedApk.java:662)
	at android.app.ContextImpl.unregisterReceiver()(ContextImpl.java:1372)
	at android.content.ContextWrapper.unregisterReceiver()(ContextWrapper.java:468)
	at com.surveymonkey.surveymonkeyandroidsdk.SMFeedbackFragment.onDestroy()(SMFeedbackFragment.java:134)
	at android.support.v4.app.Fragment.performDestroy()(Fragment.java:2586)
	at android.support.v4.app.FragmentManagerImpl.moveToState()(FragmentManager.java:1557)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState()(FragmentManager.java:1740)
	at android.support.v4.app.FragmentManagerImpl.moveToState()(FragmentManager.java:1809)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange()(FragmentManager.java:3217)
	at android.support.v4.app.FragmentManagerImpl.dispatchDestroy()(FragmentManager.java:3208)
	at android.support.v4.app.FragmentController.dispatchDestroy()(FragmentController.java:262)
	at android.support.v4.app.FragmentActivity.onDestroy()(FragmentActivity.java:343)
	at android.app.Activity.performDestroy()(Activity.java:5302)
	at android.app.Instrumentation.callActivityOnDestroy()(Instrumentation.java:1117)
	at android.app.ActivityThread.performDestroyActivity()(ActivityThread.java:3486)
	at android.app.ActivityThread.handleDestroyActivity()(ActivityThread.java:3517)
	at android.app.ActivityThread.access$1200()(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage()(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage()(Handler.java:99)
	at android.os.Looper.loop()(Looper.java:137)
	at android.app.ActivityThread.main()(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative()(Method.java:-2)
	at java.lang.reflect.Method.invoke()(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main()(ZygoteInit.java:553)
	at com.android.internal.os.ZygoteInit.main()(ZygoteInit.java:-2)
	at dalvik.system.NativeStart.main()(NativeStart.java:-2)

```
OS version : 4.3.1
Platform version: 5.14.0
Device Type: Motorola Phone
Device Name: Batmobile

**Comment by ayeung** [comment] 2017-10-19 19:55
Duplicate of https://github.com/SurveyMonkey/surveymonkey-android-sdk/issues/36

**Closed by ayeung** 2017-10-19 19:55 UTC

**Comment by doanappdev** [comment] 2017-10-31 11:46
To fix this error, we replaced SMFeedbackFragment with our own fragment which used Okhttp to make the API call to survey monkey, we then handled the response our self and displayed in a webview.
