### ISSUE TITLE
Class cast error

### ISSUE THREAD

**Issue by gondzo** [SurveyMonkey/surveymonkey-android-sdk#20] opened 2016-09-12 00:16 UTC
When submitting a survey twice with that action being disabled for a survey, a ClassCastException is thrown

com.surveymonkey.surveymonkeyandroidsdk.loaders.GetRespondentTaskLoader cannot be cast to 
com.surveymonkey.surveymonkeyandroidsdk.loaders.GetRespondentTokenTaskLoader

at SMFeedbackFragment.getToken()

This is a major issue as the entire app crashes without any error handling

**Comment by iChicory** [comment] 2017-08-10 21:24
It looks like because there used wrong hardcoded value 2, instead of RESPONDENT_TOKEN_LOADER_KEY that is constant 1
`GetRespondentTokenTaskLoader loader = (GetRespondentTokenTaskLoader) getActivity().getSupportLoaderManager().getLoader(2);
        `

**Comment by ayeung** [comment] 2017-10-18 22:15
Duplicate of https://github.com/SurveyMonkey/surveymonkey-android-sdk/issues/38

**Closed by ayeung** 2017-10-18 22:15 UTC
